name: Update Explanations

on:
  push:
    paths:
      - 'phd-thesis/main.tex'   # Trigger only if main.tex changes

jobs:
  update-md:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Run extract_lines.py
        run: python Scripts/extract_lines.py

      - name: Commit changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add Explanations/Testing.md
          git commit -m "Auto-update Testing.md" || echo "No changes to commit"
          git push

